---
abstract: 'dotf - dotfiles manager'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Capture::Tiny: '0'
  English: '0'
  File::Path: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Test::Script: '1.09'
  Test::TempDir::Tiny: '0'
  autodie: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Dotfiles
no_index:
  directory:
    - corpus
    - dzil-inc
    - examples
    - inc
    - t
    - xt
provides:
  App::Dotfiles:
    file: lib/App/Dotfiles.pm
    version: '0.001'
  App::Dotfiles::CLI:
    file: lib/App/Dotfiles/CLI.pm
    version: '0.001'
  App::Dotfiles::CLI::Command:
    file: lib/App/Dotfiles/CLI/Command.pm
    version: '0.001'
  App::Dotfiles::Error:
    file: lib/App/Dotfiles/Error.pm
    version: '0.001'
  App::Dotfiles::Linker:
    file: lib/App/Dotfiles/Linker.pm
    version: '0.001'
  App::Dotfiles::Module:
    file: lib/App/Dotfiles/Module.pm
    version: '0.001'
  App::Dotfiles::Module::Config:
    file: lib/App/Dotfiles/Module/Config.pm
    version: '0.001'
  App::Dotfiles::Role::Repository:
    file: lib/App/Dotfiles/Role/Repository.pm
    version: '0.001'
  App::Dotfiles::Role::Runtime:
    file: lib/App/Dotfiles/Role/Runtime.pm
    version: '0.001'
  App::Dotfiles::Runtime:
    file: lib/App/Dotfiles/Runtime.pm
    version: '0.001'
requires:
  Carp: '0'
  Config::Std: '0'
  File::Copy: '0'
  File::HomeDir: '0'
  File::Spec: '0'
  Getopt::Long: '0'
  Git::Wrapper: '0'
  Moo: '0'
  Moo::Role: '0'
  Path::Tiny: '0'
  Pod::Usage: '0'
  Safe::Isa: '0'
  Try::Tiny: '0'
  custom::failures: '0'
  namespace::clean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/App-Dotfiles/issues
  homepage: https://github.com/skirmess/App-Dotfiles
  repository: https://github.com/skirmess/App-Dotfiles.git
version: '0.001'
x_authority: cpan:SKIRMESS
x_serialization_backend: 'YAML::Tiny version 1.70'
