---
abstract: 'dotfiles manager'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Capture::Tiny: '0'
  Cwd: '0'
  English: '0'
  Exporter: '5.57'
  File::Basename: '0'
  File::Path: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Script: '1.09'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Dotfiles
no_index:
  directory:
    - t
    - xt
requires:
  Carp: '0'
  Config::Std: '0'
  File::Copy: '0'
  File::HomeDir::Tiny: '0'
  File::Spec: '0'
  Getopt::Long: '0'
  Git::Wrapper: '0'
  Moo: '0'
  Moo::Role: '0'
  Path::Tiny: '0'
  Pod::Usage: '1.69'
  Safe::Isa: '0'
  Try::Tiny: '0'
  custom::failures: '0'
  namespace::clean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/App-Dotfiles/issues
  homepage: https://github.com/skirmess/App-Dotfiles
  repository: https://github.com/skirmess/App-Dotfiles.git
version: '0.001'
x_spdx_expression: BSD-2-Clause-FreeBSD
