=head1 NAME

B<modules.ini>

=head1 DESCRIPTION

The B<modules.ini> file describes the dotfiles modules that should be
installed and stowed to your home directory.

=head1 EXAMPLES

=head2 B<Example 1> Use a github and a gitlab repository

In this example we use a public github repository for your Vim configuration
and a private gitlab repository for your .forward file. The vim repository
uses a different pull and push url, the forward repository uses the same url
for pulling and pusing.

  [vim]
  pull=https://github.com/YOUR_ID/dotfiles-vim.git
  push=git@github.com:YOUR_ID/dotfiles-vim.git

  [forward]
  pull=git@gitlab.com:YOUR_ID/dotfiles-forward.git

=head1 SEE ALSO

L<dotf|dotf>

=head1 AUTHOR

Sven Kirmess <sven.kirmess@kzone.ch>

=cut
