#!perl

use 5.006;
use strict;
use warnings;

use Test::More 0.88;
use Test::Fatal;

use Cwd            ();
use File::Basename ();
use File::Spec     ();
use lib File::Spec->catdir( File::Basename::dirname( Cwd::abs_path __FILE__ ), 'lib' );

use Local::Test::TempDir qw(tempdir);

use Capture::Tiny qw(capture);

use App::Dotfiles::Runtime;
use App::Dotfiles::CLI::Command;

main();

sub main {
    my $home    = tempdir();
    my $runtime = new_ok( 'App::Dotfiles::Runtime', [ home_path => $home ] );

    my $obj = new_ok( 'App::Dotfiles::CLI::Command', [ runtime => $runtime ] );

    my ( undef, undef, @result ) = capture { $obj->run_help() };
    is( $result[0], undef, '... returns undef' );

    # We don't test the output of STDOUT and STDERR.
    #
    # The output of the help subcommand is generated by Pod::Usage from
    # the POD in bin/dotf which Pod::Usage cannot find during this test.
    # The error output therefore depends on the version of Pod::Usage
    # neither can not should be tested from this test.

    #
    done_testing();

    exit 0;
}

# vim: ts=4 sts=4 sw=4 et: syntax=perl
